#!/usr/bin/env python3

"""MRI QA: Image handling"""

import sys
from package import mpb138


def main():
    modules = {'mpb138': mpb138}
    prog = sys.argv[1]
    opts = sys.argv[2:]

    # If no arguments given or help flag given, print usage
    # TODO: Use logging here
    if not prog or (prog in ["-h", "--help"]):
        print("mriqa\nusage: mriqa [module] [opts]\nmodules: mpb138")
        exit()

    # Else, pass options to relevant modules
    modules[prog].main(opts)

if __name__ == "__main__":
    main()