# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='arrays',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Patient'),
        ),
    ]
