# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrays',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
