# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20181231_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrays',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
