# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20181231_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arrays',
            new_name='Array',
        ),
    ]
